{
 "title": "Solar Finances",
 "time": { "from": "2021-09-30T23:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Self Used Energy",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "generate_energy = from(bucket: \"solarman\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solarman_daily_summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\n  sell_energy = from(bucket: \"solarman\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solarman_daily_summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy_sell\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n\njoin(tables: {g: generate_energy, s: sell_energy}, on: [\"_time\", \"plant_id\"])\n  |> map(fn: (r) => ({_value: r._value_g - r._value_s, _time: r._time, plant_id: r.plant_id}))\n  |> yield(name: \"sum\")"
    },
    { "expression": "${A}*0.20", "type": "math" }
   ]
  },
  {
   "title": "Energy Sold",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solarman\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solarman_daily_summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy_sell\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    },
    { "expression": "${A}*0.06", "type": "math" }
   ]
  },
  {
   "title": "Total Energy Bought",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solarman\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solarman_daily_summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy_buy\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    },
    { "expression": "${A}*0.2", "type": "math" }
   ]
  },
  {
   "title": "Total Energy Generated",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solarman\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solarman_daily_summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Total Energy Used",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"solarman\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"solarman_daily_summary\")\n  |> filter(fn: (r) => r[\"_field\"] == \"energy_useage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  }
 ]
}